=== paulmoyaf/CSV-XML-Java-Objetos/filesXML/productos.dtd
<!ELEMENT productos (teclado+)>
<!ELEMENT teclado (id,marca,precio,descuento,tipo,color,teclas,conector,envio,pvp)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT descuento (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT teclas (#PCDATA)>
<!ELEMENT conector (#PCDATA)>
<!ELEMENT envio (#PCDATA)>
<!ELEMENT pvp (#PCDATA)>

=== paulmoyaf/CSV-XML-Java-Objetos/files/productosOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productos SYSTEM "productos.dtd">
<productos>
        <teclado>
                <id>t32</id>
                <marca>LLACD</marca>
                <precio>915.0</precio>
                <descuento>10.0</descuento>
                <tipo>Regular</tipo>
                <color>NEGRO</color>
                <teclas>41</teclas>
                <conector>AUB</conector>
                <envio>+15€</envio>
                <pvp>839.0</pvp>
        </teclado>
        <teclado>
                <id>t322</id>
                <marca>HELA</marca>
                <precio>15.0</precio>
                <descuento>100.0</descuento>
                <tipo>Regular</tipo>
                <color>VERDE</color>
                <teclas>20</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>15.0</pvp>
        </teclado>
        <teclado>
                <id>t071</id>
                <marca>CASIO</marca>
                <precio>165.0</precio>
                <descuento>50.0</descuento>
                <tipo>Regular</tipo>
                <color>AZUL</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>98.0</pvp>
        </teclado>
        <teclado>
                <id>t123</id>
                <marca>MAC</marca>
                <precio>375.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>NEGRO</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>282.0</pvp>
        </teclado>
        <teclado>
                <id>t21</id>
                <marca>OPEL</marca>
                <precio>500.0</precio>
                <descuento>20.0</descuento>
                <tipo>Regular</tipo>
                <color>NEGRO</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>415.0</pvp>
        </teclado>
        <teclado>
                <id>t070</id>
                <marca>CASIO</marca>
                <precio>239.0</precio>
                <descuento>25.0</descuento>
                <tipo>Regular</tipo>
                <color>AZUL</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>195.0</pvp>
        </teclado>
        <teclado>
                <id>t1244</id>
                <marca>KING</marca>
                <precio>500.0</precio>
                <descuento>20.0</descuento>
                <tipo>Regular</tipo>
                <color>NEGRO</color>
                <teclas>87</teclas>
                <conector>MIDI</conector>
                <envio>+15€</envio>
                <pvp>415.0</pvp>
        </teclado>
        <teclado>
                <id>t23</id>
                <marca>OPE</marca>
                <precio>500.0</precio>
                <descuento>10.0</descuento>
                <tipo>PRIME</tipo>
                <color>PINK</color>
                <teclas>12</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>450.0</pvp>
        </teclado>
        <teclado>
                <id>t10</id>
                <marca>OPS</marca>
                <precio>500.0</precio>
                <descuento>100.0</descuento>
                <tipo>PRIME</tipo>
                <color>AOP</color>
                <teclas>12</teclas>
                <conector>MIDI</conector>
                <envio>GRATIS</envio>
                <pvp>0.0</pvp>
        </teclado>
        <teclado>
                <id>t555</id>
                <marca>FENDER</marca>
                <precio>450.0</precio>
                <descuento>10.0</descuento>
                <tipo>PRIME</tipo>
                <color>AA</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>405.0</pvp>
        </teclado>
        <teclado>
                <id>t1242</id>
                <marca>BOLS</marca>
                <precio>1240.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>GRIS</color>
                <teclas>61</teclas>
                <conector>MIDI</conector>
                <envio>GRATIS</envio>
                <pvp>930.0</pvp>
        </teclado>
        <teclado>
                <id>t24</id>
                <marca>FENDER</marca>
                <precio>2000.0</precio>
                <descuento>20.0</descuento>
                <tipo>Regular</tipo>
                <color>VERDE</color>
                <teclas>61</teclas>
                <conector>MIDI</conector>
                <envio>+15€</envio>
                <pvp>1615.0</pvp>
        </teclado>
        <teclado>
                <id>t14</id>
                <marca>PER</marca>
                <precio>1400.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>GRIS</color>
                <teclas>64</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>1050.0</pvp>
        </teclado>
        <teclado>
                <id>t003</id>
                <marca>YAMAHA</marca>
                <precio>1000.0</precio>
                <descuento>25.0</descuento>
                <tipo>Regular</tipo>
                <color>BLANCO</color>
                <teclas>82</teclas>
                <conector>MIDI</conector>
                <envio>+15€</envio>
                <pvp>765.0</pvp>
        </teclado>
        <teclado>
                <id>txss</id>
                <marca>FENDER</marca>
                <precio>200.0</precio>
                <descuento>23.0</descuento>
                <tipo>Regular</tipo>
                <color>VRDE</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>169.0</pvp>
        </teclado>
        <teclado>
                <id>t1541</id>
                <marca>SONIX</marca>
                <precio>200.0</precio>
                <descuento>20.0</descuento>
                <tipo>Regular</tipo>
                <color>VERDE</color>
                <teclas>6</teclas>
                <conector>MIDI</conector>
                <envio>+15€</envio>
                <pvp>175.0</pvp>
        </teclado>
        <teclado>
                <id>ta</id>
                <marca>PEN</marca>
                <precio>400.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>NEGRO</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>300.0</pvp>
        </teclado>
        <teclado>
                <id>t65</id>
                <marca>YAMAHA</marca>
                <precio>1000.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>NEGRO</color>
                <teclas>61</teclas>
                <conector>XFIND</conector>
                <envio>GRATIS</envio>
                <pvp>750.0</pvp>
        </teclado>
</productos>

=== paulmoyaf/CSV-XML-Java-Objetos/filesXML/productosAttribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productos SYSTEM "productos.dtd">
<productos>
        <teclado id_at="t32">
                <marca>LLACD</marca>
                <precio>915.0</precio>
                <descuento>10.0</descuento>
                <tipo>Regular</tipo>
                <color>NEGRO</color>
                <teclas>41</teclas>
                <conector>AUB</conector>
                <envio>+15€</envio>
                <pvp>839.0</pvp>
        </teclado>
        <teclado id_at="t322">
                <marca>HELA</marca>
                <precio>15.0</precio>
                <descuento>100.0</descuento>
                <tipo>Regular</tipo>
                <color>VERDE</color>
                <teclas>20</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>15.0</pvp>
        </teclado>
        <teclado id_at="t071">
                <marca>CASIO</marca>
                <precio>165.0</precio>
                <descuento>50.0</descuento>
                <tipo>Regular</tipo>
                <color>AZUL</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>98.0</pvp>
        </teclado>
        <teclado id_at="t123">
                <marca>MAC</marca>
                <precio>375.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>NEGRO</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>282.0</pvp>
        </teclado>
        <teclado id_at="t21">
                <marca>OPEL</marca>
                <precio>500.0</precio>
                <descuento>20.0</descuento>
                <tipo>Regular</tipo>
                <color>NEGRO</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>415.0</pvp>
        </teclado>
        <teclado id_at="t070">
                <marca>CASIO</marca>
                <precio>239.0</precio>
                <descuento>25.0</descuento>
                <tipo>Regular</tipo>
                <color>AZUL</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>195.0</pvp>
        </teclado>
        <teclado id_at="t1244">
                <marca>KING</marca>
                <precio>500.0</precio>
                <descuento>20.0</descuento>
                <tipo>Regular</tipo>
                <color>NEGRO</color>
                <teclas>87</teclas>
                <conector>MIDI</conector>
                <envio>+15€</envio>
                <pvp>415.0</pvp>
        </teclado>
        <teclado id_at="t23">
                <marca>OPE</marca>
                <precio>500.0</precio>
                <descuento>10.0</descuento>
                <tipo>PRIME</tipo>
                <color>PINK</color>
                <teclas>12</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>450.0</pvp>
        </teclado>
        <teclado id_at="t10">
                <marca>OPS</marca>
                <precio>500.0</precio>
                <descuento>100.0</descuento>
                <tipo>PRIME</tipo>
                <color>AOP</color>
                <teclas>12</teclas>
                <conector>MIDI</conector>
                <envio>GRATIS</envio>
                <pvp>0.0</pvp>
        </teclado>
        <teclado id_at="t555">
                <marca>FENDER</marca>
                <precio>450.0</precio>
                <descuento>10.0</descuento>
                <tipo>PRIME</tipo>
                <color>AA</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>405.0</pvp>
        </teclado>
        <teclado id_at="t1242">
                <marca>BOLS</marca>
                <precio>1240.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>GRIS</color>
                <teclas>61</teclas>
                <conector>MIDI</conector>
                <envio>GRATIS</envio>
                <pvp>930.0</pvp>
        </teclado>
        <teclado id_at="t24">
                <marca>FENDER</marca>
                <precio>2000.0</precio>
                <descuento>20.0</descuento>
                <tipo>Regular</tipo>
                <color>VERDE</color>
                <teclas>61</teclas>
                <conector>MIDI</conector>
                <envio>+15€</envio>
                <pvp>1615.0</pvp>
        </teclado>
        <teclado id_at="t14">
                <marca>PER</marca>
                <precio>1400.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>GRIS</color>
                <teclas>64</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>1050.0</pvp>
        </teclado>
        <teclado id_at="t003">
                <marca>YAMAHA</marca>
                <precio>1000.0</precio>
                <descuento>25.0</descuento>
                <tipo>Regular</tipo>
                <color>BLANCO</color>
                <teclas>82</teclas>
                <conector>MIDI</conector>
                <envio>+15€</envio>
                <pvp>765.0</pvp>
        </teclado>
        <teclado id_at="txss">
                <marca>FENDER</marca>
                <precio>200.0</precio>
                <descuento>23.0</descuento>
                <tipo>Regular</tipo>
                <color>VRDE</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>+15€</envio>
                <pvp>169.0</pvp>
        </teclado>
        <teclado id_at="t1541">
                <marca>SONIX</marca>
                <precio>200.0</precio>
                <descuento>20.0</descuento>
                <tipo>Regular</tipo>
                <color>VERDE</color>
                <teclas>6</teclas>
                <conector>MIDI</conector>
                <envio>+15€</envio>
                <pvp>175.0</pvp>
        </teclado>
        <teclado id_at="ta">
                <marca>PEN</marca>
                <precio>400.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>NEGRO</color>
                <teclas>61</teclas>
                <conector>USB</conector>
                <envio>GRATIS</envio>
                <pvp>300.0</pvp>
        </teclado>
        <teclado id_at="t65">
                <marca>YAMAHA</marca>
                <precio>1000.0</precio>
                <descuento>25.0</descuento>
                <tipo>PRIME</tipo>
                <color>NEGRO</color>
                <teclas>61</teclas>
                <conector>XFIND</conector>
                <envio>GRATIS</envio>
                <pvp>750.0</pvp>
        </teclado>
</productos>
